export const API_ROOT = 'http://localhost:8080/'
export const SUBCRIPTION_ENDPOINT = 'http://holidaycalendar.com/ics/?countryCodes='
export const GET_COUNTRIES_ENDPOINT = API_ROOT + 'api/location/countries'
export const GET_HOLIDAYS_ENDPOINT = API_ROOT + 'api/holiday'
export const SEND_SUBSCRIPTION_ENDPOINT = API_ROOT + 'api/subscription'
