export const countries = [
    { isoAlpha2Code: 'AD', commonName: 'Andorra', phone: '376' },
    {
        isoAlpha2Code: 'AE',
        commonName: 'United Arab Emirates',
        phone: '971',
    },
    { isoAlpha2Code: 'AF', commonName: 'Afghanistan', phone: '93' },
    {
        isoAlpha2Code: 'AG',
        commonName: 'Antigua and Barbuda',
        phone: '1-268',
    },
    { isoAlpha2Code: 'AI', commonName: 'Anguilla', phone: '1-264' },
    { isoAlpha2Code: 'AL', commonName: 'Albania', phone: '355' },
    { isoAlpha2Code: 'AM', commonName: 'Armenia', phone: '374' },
    { isoAlpha2Code: 'AO', commonName: 'Angola', phone: '244' },
    { isoAlpha2Code: 'AQ', commonName: 'Antarctica', phone: '672' },
    { isoAlpha2Code: 'AR', commonName: 'Argentina', phone: '54' },
    { isoAlpha2Code: 'AS', commonName: 'American Samoa', phone: '1-684' },
    { isoAlpha2Code: 'AT', commonName: 'Austria', phone: '43' },
    {
        isoAlpha2Code: 'AU',
        commonName: 'Australia',
        phone: '61',
        suggested: true,
    },
    { isoAlpha2Code: 'AW', commonName: 'Aruba', phone: '297' },
    { isoAlpha2Code: 'AX', commonName: 'Alland Islands', phone: '358' },
    { isoAlpha2Code: 'AZ', commonName: 'Azerbaijan', phone: '994' },
    {
        isoAlpha2Code: 'BA',
        commonName: 'Bosnia and Herzegovina',
        phone: '387',
    },
    { isoAlpha2Code: 'BB', commonName: 'Barbados', phone: '1-246' },
    { isoAlpha2Code: 'BD', commonName: 'Bangladesh', phone: '880' },
    { isoAlpha2Code: 'BE', commonName: 'Belgium', phone: '32' },
    { isoAlpha2Code: 'BF', commonName: 'Burkina Faso', phone: '226' },
    { isoAlpha2Code: 'BG', commonName: 'Bulgaria', phone: '359' },
    { isoAlpha2Code: 'BH', commonName: 'Bahrain', phone: '973' },
    { isoAlpha2Code: 'BI', commonName: 'Burundi', phone: '257' },
    { isoAlpha2Code: 'BJ', commonName: 'Benin', phone: '229' },
    { isoAlpha2Code: 'BL', commonName: 'Saint Barthelemy', phone: '590' },
    { isoAlpha2Code: 'BM', commonName: 'Bermuda', phone: '1-441' },
    { isoAlpha2Code: 'BN', commonName: 'Brunei Darussalam', phone: '673' },
    { isoAlpha2Code: 'BO', commonName: 'Bolivia', phone: '591' },
    { isoAlpha2Code: 'BR', commonName: 'Brazil', phone: '55' },
    { isoAlpha2Code: 'BS', commonName: 'Bahamas', phone: '1-242' },
    { isoAlpha2Code: 'BT', commonName: 'Bhutan', phone: '975' },
    { isoAlpha2Code: 'BV', commonName: 'Bouvet Island', phone: '47' },
    { isoAlpha2Code: 'BW', commonName: 'Botswana', phone: '267' },
    { isoAlpha2Code: 'BY', commonName: 'Belarus', phone: '375' },
    { isoAlpha2Code: 'BZ', commonName: 'Belize', phone: '501' },
    {
        isoAlpha2Code: 'CA',
        commonName: 'Canada',
        phone: '1',
        suggested: true,
    },
    {
        isoAlpha2Code: 'CC',
        commonName: 'Cocos (Keeling) Islands',
        phone: '61',
    },
    {
        isoAlpha2Code: 'CD',
        commonName: 'Congo, Democratic Republic of the',
        phone: '243',
    },
    {
        isoAlpha2Code: 'CF',
        commonName: 'Central African Republic',
        phone: '236',
    },
    {
        isoAlpha2Code: 'CG',
        commonName: 'Congo, Republic of the',
        phone: '242',
    },
    { isoAlpha2Code: 'CH', commonName: 'Switzerland', phone: '41' },
    { isoAlpha2Code: 'CI', commonName: "Cote d'Ivoire", phone: '225' },
    { isoAlpha2Code: 'CK', commonName: 'Cook Islands', phone: '682' },
    { isoAlpha2Code: 'CL', commonName: 'Chile', phone: '56' },
    { isoAlpha2Code: 'CM', commonName: 'Cameroon', phone: '237' },
    { isoAlpha2Code: 'CN', commonName: 'China', phone: '86' },
    { isoAlpha2Code: 'CO', commonName: 'Colombia', phone: '57' },
    { isoAlpha2Code: 'CR', commonName: 'Costa Rica', phone: '506' },
    { isoAlpha2Code: 'CU', commonName: 'Cuba', phone: '53' },
    { isoAlpha2Code: 'CV', commonName: 'Cape Verde', phone: '238' },
    { isoAlpha2Code: 'CW', commonName: 'Curacao', phone: '599' },
    { isoAlpha2Code: 'CX', commonName: 'Christmas Island', phone: '61' },
    { isoAlpha2Code: 'CY', commonName: 'Cyprus', phone: '357' },
    { isoAlpha2Code: 'CZ', commonName: 'Czech Republic', phone: '420' },
    {
        isoAlpha2Code: 'DE',
        commonName: 'Germany',
        phone: '49',
        suggested: true,
    },
    { isoAlpha2Code: 'DJ', commonName: 'Djibouti', phone: '253' },
    { isoAlpha2Code: 'DK', commonName: 'Denmark', phone: '45' },
    { isoAlpha2Code: 'DM', commonName: 'Dominica', phone: '1-767' },
    {
        isoAlpha2Code: 'DO',
        commonName: 'Dominican Republic',
        phone: '1-809',
    },
    { isoAlpha2Code: 'DZ', commonName: 'Algeria', phone: '213' },
    { isoAlpha2Code: 'EC', commonName: 'Ecuador', phone: '593' },
    { isoAlpha2Code: 'EE', commonName: 'Estonia', phone: '372' },
    { isoAlpha2Code: 'EG', commonName: 'Egypt', phone: '20' },
    { isoAlpha2Code: 'EH', commonName: 'Western Sahara', phone: '212' },
    { isoAlpha2Code: 'ER', commonName: 'Eritrea', phone: '291' },
    { isoAlpha2Code: 'ES', commonName: 'Spain', phone: '34' },
    { isoAlpha2Code: 'ET', commonName: 'Ethiopia', phone: '251' },
    { isoAlpha2Code: 'FI', commonName: 'Finland', phone: '358' },
    { isoAlpha2Code: 'FJ', commonName: 'Fiji', phone: '679' },
    {
        isoAlpha2Code: 'FK',
        commonName: 'Falkland Islands (Malvinas)',
        phone: '500',
    },
    {
        isoAlpha2Code: 'FM',
        commonName: 'Micronesia, Federated States of',
        phone: '691',
    },
    { isoAlpha2Code: 'FO', commonName: 'Faroe Islands', phone: '298' },
    {
        isoAlpha2Code: 'FR',
        commonName: 'France',
        phone: '33',
        suggested: true,
    },
    { isoAlpha2Code: 'GA', commonName: 'Gabon', phone: '241' },
    { isoAlpha2Code: 'GB', commonName: 'United Kingdom', phone: '44' },
    { isoAlpha2Code: 'GD', commonName: 'Grenada', phone: '1-473' },
    { isoAlpha2Code: 'GE', commonName: 'Georgia', phone: '995' },
    { isoAlpha2Code: 'GF', commonName: 'French Guiana', phone: '594' },
    { isoAlpha2Code: 'GG', commonName: 'Guernsey', phone: '44' },
    { isoAlpha2Code: 'GH', commonName: 'Ghana', phone: '233' },
    { isoAlpha2Code: 'GI', commonName: 'Gibraltar', phone: '350' },
    { isoAlpha2Code: 'GL', commonName: 'Greenland', phone: '299' },
    { isoAlpha2Code: 'GM', commonName: 'Gambia', phone: '220' },
    { isoAlpha2Code: 'GN', commonName: 'Guinea', phone: '224' },
    { isoAlpha2Code: 'GP', commonName: 'Guadeloupe', phone: '590' },
    { isoAlpha2Code: 'GQ', commonName: 'Equatorial Guinea', phone: '240' },
    { isoAlpha2Code: 'GR', commonName: 'Greece', phone: '30' },
    {
        isoAlpha2Code: 'GS',
        commonName: 'South Georgia and the South Sandwich Islands',
        phone: '500',
    },
    { isoAlpha2Code: 'GT', commonName: 'Guatemala', phone: '502' },
    { isoAlpha2Code: 'GU', commonName: 'Guam', phone: '1-671' },
    { isoAlpha2Code: 'GW', commonName: 'Guinea-Bissau', phone: '245' },
    { isoAlpha2Code: 'GY', commonName: 'Guyana', phone: '592' },
    { isoAlpha2Code: 'HK', commonName: 'Hong Kong', phone: '852' },
    {
        isoAlpha2Code: 'HM',
        commonName: 'Heard Island and McDonald Islands',
        phone: '672',
    },
    { isoAlpha2Code: 'HN', commonName: 'Honduras', phone: '504' },
    { isoAlpha2Code: 'HR', commonName: 'Croatia', phone: '385' },
    { isoAlpha2Code: 'HT', commonName: 'Haiti', phone: '509' },
    { isoAlpha2Code: 'HU', commonName: 'Hungary', phone: '36' },
    { isoAlpha2Code: 'ID', commonName: 'Indonesia', phone: '62' },
    { isoAlpha2Code: 'IE', commonName: 'Ireland', phone: '353' },
    { isoAlpha2Code: 'IL', commonName: 'Israel', phone: '972' },
    { isoAlpha2Code: 'IM', commonName: 'Isle of Man', phone: '44' },
    { isoAlpha2Code: 'IN', commonName: 'India', phone: '91' },
    {
        isoAlpha2Code: 'IO',
        commonName: 'British Indian Ocean Territory',
        phone: '246',
    },
    { isoAlpha2Code: 'IQ', commonName: 'Iraq', phone: '964' },
    {
        isoAlpha2Code: 'IR',
        commonName: 'Iran, Islamic Republic of',
        phone: '98',
    },
    { isoAlpha2Code: 'IS', commonName: 'Iceland', phone: '354' },
    { isoAlpha2Code: 'IT', commonName: 'Italy', phone: '39' },
    { isoAlpha2Code: 'JE', commonName: 'Jersey', phone: '44' },
    { isoAlpha2Code: 'JM', commonName: 'Jamaica', phone: '1-876' },
    { isoAlpha2Code: 'JO', commonName: 'Jordan', phone: '962' },
    {
        isoAlpha2Code: 'JP',
        commonName: 'Japan',
        phone: '81',
        suggested: true,
    },
    { isoAlpha2Code: 'KE', commonName: 'Kenya', phone: '254' },
    { isoAlpha2Code: 'KG', commonName: 'Kyrgyzstan', phone: '996' },
    { isoAlpha2Code: 'KH', commonName: 'Cambodia', phone: '855' },
    { isoAlpha2Code: 'KI', commonName: 'Kiribati', phone: '686' },
    { isoAlpha2Code: 'KM', commonName: 'Comoros', phone: '269' },
    {
        isoAlpha2Code: 'KN',
        commonName: 'Saint Kitts and Nevis',
        phone: '1-869',
    },
    {
        isoAlpha2Code: 'KP',
        commonName: "Korea, Democratic People's Republic of",
        phone: '850',
    },
    { isoAlpha2Code: 'KR', commonName: 'Korea, Republic of', phone: '82' },
    { isoAlpha2Code: 'KW', commonName: 'Kuwait', phone: '965' },
    { isoAlpha2Code: 'KY', commonName: 'Cayman Islands', phone: '1-345' },
    { isoAlpha2Code: 'KZ', commonName: 'Kazakhstan', phone: '7' },
    {
        isoAlpha2Code: 'LA',
        commonName: "Lao People's Democratic Republic",
        phone: '856',
    },
    { isoAlpha2Code: 'LB', commonName: 'Lebanon', phone: '961' },
    { isoAlpha2Code: 'LC', commonName: 'Saint Lucia', phone: '1-758' },
    { isoAlpha2Code: 'LI', commonName: 'Liechtenstein', phone: '423' },
    { isoAlpha2Code: 'LK', commonName: 'Sri Lanka', phone: '94' },
    { isoAlpha2Code: 'LR', commonName: 'Liberia', phone: '231' },
    { isoAlpha2Code: 'LS', commonName: 'Lesotho', phone: '266' },
    { isoAlpha2Code: 'LT', commonName: 'Lithuania', phone: '370' },
    { isoAlpha2Code: 'LU', commonName: 'Luxembourg', phone: '352' },
    { isoAlpha2Code: 'LV', commonName: 'Latvia', phone: '371' },
    { isoAlpha2Code: 'LY', commonName: 'Libya', phone: '218' },
    { isoAlpha2Code: 'MA', commonName: 'Morocco', phone: '212' },
    { isoAlpha2Code: 'MC', commonName: 'Monaco', phone: '377' },
    {
        isoAlpha2Code: 'MD',
        commonName: 'Moldova, Republic of',
        phone: '373',
    },
    { isoAlpha2Code: 'ME', commonName: 'Montenegro', phone: '382' },
    {
        isoAlpha2Code: 'MF',
        commonName: 'Saint Martin (French part)',
        phone: '590',
    },
    { isoAlpha2Code: 'MG', commonName: 'Madagascar', phone: '261' },
    { isoAlpha2Code: 'MH', commonName: 'Marshall Islands', phone: '692' },
    {
        isoAlpha2Code: 'MK',
        commonName: 'Macedonia, the Former Yugoslav Republic of',
        phone: '389',
    },
    { isoAlpha2Code: 'ML', commonName: 'Mali', phone: '223' },
    { isoAlpha2Code: 'MM', commonName: 'Myanmar', phone: '95' },
    { isoAlpha2Code: 'MN', commonName: 'Mongolia', phone: '976' },
    { isoAlpha2Code: 'MO', commonName: 'Macao', phone: '853' },
    {
        isoAlpha2Code: 'MP',
        commonName: 'Northern Mariana Islands',
        phone: '1-670',
    },
    { isoAlpha2Code: 'MQ', commonName: 'Martinique', phone: '596' },
    { isoAlpha2Code: 'MR', commonName: 'Mauritania', phone: '222' },
    { isoAlpha2Code: 'MS', commonName: 'Montserrat', phone: '1-664' },
    { isoAlpha2Code: 'MT', commonName: 'Malta', phone: '356' },
    { isoAlpha2Code: 'MU', commonName: 'Mauritius', phone: '230' },
    { isoAlpha2Code: 'MV', commonName: 'Maldives', phone: '960' },
    { isoAlpha2Code: 'MW', commonName: 'Malawi', phone: '265' },
    { isoAlpha2Code: 'MX', commonName: 'Mexico', phone: '52' },
    { isoAlpha2Code: 'MY', commonName: 'Malaysia', phone: '60' },
    { isoAlpha2Code: 'MZ', commonName: 'Mozambique', phone: '258' },
    { isoAlpha2Code: 'NA', commonName: 'Namibia', phone: '264' },
    { isoAlpha2Code: 'NC', commonName: 'New Caledonia', phone: '687' },
    { isoAlpha2Code: 'NE', commonName: 'Niger', phone: '227' },
    { isoAlpha2Code: 'NF', commonName: 'Norfolk Island', phone: '672' },
    { isoAlpha2Code: 'NG', commonName: 'Nigeria', phone: '234' },
    { isoAlpha2Code: 'NI', commonName: 'Nicaragua', phone: '505' },
    { isoAlpha2Code: 'NL', commonName: 'Netherlands', phone: '31' },
    { isoAlpha2Code: 'NO', commonName: 'Norway', phone: '47' },
    { isoAlpha2Code: 'NP', commonName: 'Nepal', phone: '977' },
    { isoAlpha2Code: 'NR', commonName: 'Nauru', phone: '674' },
    { isoAlpha2Code: 'NU', commonName: 'Niue', phone: '683' },
    { isoAlpha2Code: 'NZ', commonName: 'New Zealand', phone: '64' },
    { isoAlpha2Code: 'OM', commonName: 'Oman', phone: '968' },
    { isoAlpha2Code: 'PA', commonName: 'Panama', phone: '507' },
    { isoAlpha2Code: 'PE', commonName: 'Peru', phone: '51' },
    { isoAlpha2Code: 'PF', commonName: 'French Polynesia', phone: '689' },
    { isoAlpha2Code: 'PG', commonName: 'Papua New Guinea', phone: '675' },
    { isoAlpha2Code: 'PH', commonName: 'Philippines', phone: '63' },
    { isoAlpha2Code: 'PK', commonName: 'Pakistan', phone: '92' },
    { isoAlpha2Code: 'PL', commonName: 'Poland', phone: '48' },
    {
        isoAlpha2Code: 'PM',
        commonName: 'Saint Pierre and Miquelon',
        phone: '508',
    },
    { isoAlpha2Code: 'PN', commonName: 'Pitcairn', phone: '870' },
    { isoAlpha2Code: 'PR', commonName: 'Puerto Rico', phone: '1' },
    {
        isoAlpha2Code: 'PS',
        commonName: 'Palestine, State of',
        phone: '970',
    },
    { isoAlpha2Code: 'PT', commonName: 'Portugal', phone: '351' },
    { isoAlpha2Code: 'PW', commonName: 'Palau', phone: '680' },
    { isoAlpha2Code: 'PY', commonName: 'Paraguay', phone: '595' },
    { isoAlpha2Code: 'QA', commonName: 'Qatar', phone: '974' },
    { isoAlpha2Code: 'RE', commonName: 'Reunion', phone: '262' },
    { isoAlpha2Code: 'RO', commonName: 'Romania', phone: '40' },
    { isoAlpha2Code: 'RS', commonName: 'Serbia', phone: '381' },
    { isoAlpha2Code: 'RU', commonName: 'Russian Federation', phone: '7' },
    { isoAlpha2Code: 'RW', commonName: 'Rwanda', phone: '250' },
    { isoAlpha2Code: 'SA', commonName: 'Saudi Arabia', phone: '966' },
    { isoAlpha2Code: 'SB', commonName: 'Solomon Islands', phone: '677' },
    { isoAlpha2Code: 'SC', commonName: 'Seychelles', phone: '248' },
    { isoAlpha2Code: 'SD', commonName: 'Sudan', phone: '249' },
    { isoAlpha2Code: 'SE', commonName: 'Sweden', phone: '46' },
    { isoAlpha2Code: 'SG', commonName: 'Singapore', phone: '65' },
    { isoAlpha2Code: 'SH', commonName: 'Saint Helena', phone: '290' },
    { isoAlpha2Code: 'SI', commonName: 'Slovenia', phone: '386' },
    {
        isoAlpha2Code: 'SJ',
        commonName: 'Svalbard and Jan Mayen',
        phone: '47',
    },
    { isoAlpha2Code: 'SK', commonName: 'Slovakia', phone: '421' },
    { isoAlpha2Code: 'SL', commonName: 'Sierra Leone', phone: '232' },
    { isoAlpha2Code: 'SM', commonName: 'San Marino', phone: '378' },
    { isoAlpha2Code: 'SN', commonName: 'Senegal', phone: '221' },
    { isoAlpha2Code: 'SO', commonName: 'Somalia', phone: '252' },
    { isoAlpha2Code: 'SR', commonName: 'Suriname', phone: '597' },
    { isoAlpha2Code: 'SS', commonName: 'South Sudan', phone: '211' },
    {
        isoAlpha2Code: 'ST',
        commonName: 'Sao Tome and Principe',
        phone: '239',
    },
    { isoAlpha2Code: 'SV', commonName: 'El Salvador', phone: '503' },
    {
        isoAlpha2Code: 'SX',
        commonName: 'Sint Maarten (Dutch part)',
        phone: '1-721',
    },
    {
        isoAlpha2Code: 'SY',
        commonName: 'Syrian Arab Republic',
        phone: '963',
    },
    { isoAlpha2Code: 'SZ', commonName: 'Swaziland', phone: '268' },
    {
        isoAlpha2Code: 'TC',
        commonName: 'Turks and Caicos Islands',
        phone: '1-649',
    },
    { isoAlpha2Code: 'TD', commonName: 'Chad', phone: '235' },
    {
        isoAlpha2Code: 'TF',
        commonName: 'French Southern Territories',
        phone: '262',
    },
    { isoAlpha2Code: 'TG', commonName: 'Togo', phone: '228' },
    { isoAlpha2Code: 'TH', commonName: 'Thailand', phone: '66' },
    { isoAlpha2Code: 'TJ', commonName: 'Tajikistan', phone: '992' },
    { isoAlpha2Code: 'TK', commonName: 'Tokelau', phone: '690' },
    { isoAlpha2Code: 'TL', commonName: 'Timor-Leste', phone: '670' },
    { isoAlpha2Code: 'TM', commonName: 'Turkmenistan', phone: '993' },
    { isoAlpha2Code: 'TN', commonName: 'Tunisia', phone: '216' },
    { isoAlpha2Code: 'TO', commonName: 'Tonga', phone: '676' },
    { isoAlpha2Code: 'TR', commonName: 'Turkey', phone: '90' },
    {
        isoAlpha2Code: 'TT',
        commonName: 'Trinidad and Tobago',
        phone: '1-868',
    },
    { isoAlpha2Code: 'TV', commonName: 'Tuvalu', phone: '688' },
    {
        isoAlpha2Code: 'TW',
        commonName: 'Taiwan, Province of China',
        phone: '886',
    },
    {
        isoAlpha2Code: 'TZ',
        commonName: 'United Republic of Tanzania',
        phone: '255',
    },
    { isoAlpha2Code: 'UA', commonName: 'Ukraine', phone: '380' },
    { isoAlpha2Code: 'UG', commonName: 'Uganda', phone: '256' },
    {
        isoAlpha2Code: 'US',
        commonName: 'United States',
        phone: '1',
        suggested: true,
    },
    { isoAlpha2Code: 'UY', commonName: 'Uruguay', phone: '598' },
    { isoAlpha2Code: 'UZ', commonName: 'Uzbekistan', phone: '998' },
    {
        isoAlpha2Code: 'VA',
        commonName: 'Holy See (Vatican City State)',
        phone: '379',
    },
    {
        isoAlpha2Code: 'VC',
        commonName: 'Saint Vincent and the Grenadines',
        phone: '1-784',
    },
    { isoAlpha2Code: 'VE', commonName: 'Venezuela', phone: '58' },
    {
        isoAlpha2Code: 'VG',
        commonName: 'British Virgin Islands',
        phone: '1-284',
    },
    {
        isoAlpha2Code: 'VI',
        commonName: 'US Virgin Islands',
        phone: '1-340',
    },
    { isoAlpha2Code: 'VN', commonName: 'Vietnam', phone: '84' },
    { isoAlpha2Code: 'VU', commonName: 'Vanuatu', phone: '678' },
    { isoAlpha2Code: 'WF', commonName: 'Wallis and Futuna', phone: '681' },
    { isoAlpha2Code: 'WS', commonName: 'Samoa', phone: '685' },
    { isoAlpha2Code: 'XK', commonName: 'Kosovo', phone: '383' },
    { isoAlpha2Code: 'YE', commonName: 'Yemen', phone: '967' },
    { isoAlpha2Code: 'YT', commonName: 'Mayotte', phone: '262' },
    { isoAlpha2Code: 'ZA', commonName: 'South Africa', phone: '27' },
    { isoAlpha2Code: 'ZM', commonName: 'Zambia', phone: '260' },
    { isoAlpha2Code: 'ZW', commonName: 'Zimbabwe', phone: '263' },
];
